version: '3.3'
services:
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: REPLICATION:PLAINTEXT,CLIENT:SASL_PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: CLIENT://:9092,REPLICATION://:9093
      KAFKA_LISTENERS: CLIENT://0.0.0.0:9092,REPLICATION://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: CLIENT
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN    
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN  
      CUSTOM_INIT_SCRIPT: "export KAFKA_OPTS=-Djava.security.auth.login.config=/kafka_jaas.conf"
    volumes:
       - /mnt/vdb1/kafka/zkjaas.conf:/kafka_jaas.conf

    networks:
      - zookeeper_zk-net
   
      
      
networks:
  zookeeper_zk-net:
    external:
      name: zookeeper_zk-net
